//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bien
    {
        public Bien()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public int ID { get; set; }
        public string Adresse { get; set; }
        public string City { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public Nullable<int> PricePerNight { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Description { get; set; }
        public Nullable<int> OptionID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual Option Option { get; set; }
    }
}
