//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public Option()
        {
            this.Biens = new HashSet<Bien>();
        }
    
        public int ID { get; set; }
        public int Surface { get; set; }
        public int Rooms { get; set; }
        public int Bathrooms { get; set; }
        public bool Garage { get; set; }
        public bool Garden { get; set; }
        public bool Terrace { get; set; }
        public bool WashingMachine { get; set; }
        public bool DishWasher { get; set; }
        public bool BabyBed { get; set; }
    
        public virtual ICollection<Bien> Biens { get; set; }
    }
}
